title: blog of springdong
description: personal blog
author: Springdong
github: https://github.com/spr1ngd
about: 就职于Uinnova，工作内容IOT可视化平台开发
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/spr1ngd"

share:
  twitter_username: 
  fb_appid: 

urls:
    - text : UChart
      url : 
    - text: Blog
      url: /projects/
    - text: About Me
      url: /about/

url: "https://spr1ngd.github.io"
baseurl: "https://spr1ngd.github.io"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

theme: jekyll-theme-cayman